SharedData = {}

SharedData.Weapons = {
    WEAPON_LASSO = {
        Name        = "Laço",
        Desc        = "Usado ao amarrar alguém. O reforçado tem uso ilimitado",
        AttachPoint = "",            
        HashName    = "WEAPON_LASSO", 
        Weight      = 0.50,          
    },
    WEAPON_LASSO_REINFORCED = {
        Name        = "Laço Reforçado",
        Desc        = "Sem limite de uso para amarrar",
        AttachPoint = "",
        HashName    = "WEAPON_LASSO_REINFORCED",
        Weight      = 0.55,
    },
    WEAPON_MELEE_KNIFE = {
        Name = "Faca",
        Desc = "Faca usada principalmente para esfolar animais",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE",
        Weight = 0.33,
    },
    WEAPON_MELEE_KNIFE_RUSTIC = {
        Name = "Faca Rústica",
        Desc = "Faca de aparência antiga, ainda será útil?",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_RUSTIC",
        Weight = 0.40,
    },
    WEAPON_MELEE_KNIFE_HORROR = {
        Name = "Faca Horror",
        Desc = "Esta faca foi usada para várias coisas desagradáveis",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_HORROR",
        Weight = 0.40,
    },
    WEAPON_MELEE_KNIFE_CIVIL_WAR = {
        Name = "Faca Guerra Civil",
        Desc = "Uma faca com muita história",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_CIVIL_WAR",
        Weight = 0.45,
    },
    WEAPON_MELEE_KNIFE_JAWBONE = {
        Name = "Faca de Mandíbula",
        Desc = "Uma faca feita de ossos antigos",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_JAWBONE",
        Weight = 0.37,
    },
    WEAPON_MELEE_KNIFE_MINER = {
        Name = "Faca do Mineiro",
        Desc = "O melhor amigo do mineiro",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_MINER",
        Weight = 0.40,
    },
    WEAPON_MELEE_KNIFE_VAMPIRE = {
        Name = "Faca Vampiro",
        Desc = "Eles não podem ser reais...",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_VAMPIRE",
        Weight = 0.39,
    },
    WEAPON_MELEE_CLEAVER = {
        Name = "Cutelo",
        Desc = "Assustador, mas útil",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_CLEAVER",
        Weight = 0.73,
    },
    WEAPON_MELEE_HATCHET = {
        Name = "Machado",
        Desc = "Um pedaço de madeira com uma lâmina",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_HATCHET",
        Weight = 1.05,
    },
    WEAPON_MELEE_HATCHET_DOUBLE_BIT = {
        Name = "Machado de Duas Lâminas",
        Desc = "Um pedaço de madeira com duas lâminas",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_HATCHET_DOUBLE_BIT",
        Weight = 1.15,
    },
    WEAPON_MELEE_HATCHET_HEWING = {
        Name = "Machado de Entalhe",
        Desc = "Dizem que este machado é mágico",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_HATCHET_HEWING",
        Weight = 1.10,
    },
    WEAPON_MELEE_HATCHET_HUNTER = {
        Name = "Machado de Caçador",
        Desc = "O melhor amigo do caçador",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_HATCHET_HUNTER",
        Weight = 1.15,
    },
    WEAPON_MELEE_HATCHET_VIKING = {
        Name = "Machado Viking",
        Desc = "Cheira a peixe e sal",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_HATCHET_VIKING",
        Weight = 1.20,
    },
    WEAPON_THROWN_TOMAHAWK = {
        Name = "Tomahawk",
        Desc = "Uma arma digna de um guerreiro",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_TOMAHAWK",
        Weight = 1.30,
    },
    WEAPON_THROWN_TOMAHAWK_ANCIENT = {
        Name = "Tomahawk Antigo",
        Desc = "Este é antigo",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_TOMAHAWK_ANCIENT",
        Weight = 1.50,
    },
    WEAPON_THROWN_THROWING_KNIVES = {
        Name = "Facas de Arremesso",
        Desc = "As pessoas adoram brincar com elas",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_THROWING_KNIVES",
        Weight = 1.05,
    },
    WEAPON_MELEE_MACHETE = {
        Name = "Facão",
        Desc = "Útil na selva",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_MACHETE",
        Weight = 1.3,
    },
    WEAPON_BOW = {
        Name = "Arco",
        Desc = "Uma arma simples, mas eficaz",
        AttachPoint = "",
        HashName = "WEAPON_BOW",
        Weight = 0.85,
    },
    WEAPON_PISTOL_SEMIAUTO = {
        Name = "Pistola Semi-Automática",
        Desc = "arma de repetição de câmara única",
        AttachPoint = "",
        HashName = 'WEAPON_PISTOL_SEMIAUTO',
        Weight = 1.18,
    },
    WEAPON_PISTOL_MAUSER = {
        Name = "Pistola Mauser",
        Desc = "pistola semi-automática originalmente produzida pelo fabricante alemão Mauser",
        AttachPoint = "",
        HashName = "WEAPON_PISTOL_MAUSER",
        Weight = 1.13,
    },
    WEAPON_PISTOL_VOLCANIC = {
        Name = "Pistola Volcanic",
        Desc = "uma versão aprimorada da munição Rocket Ball",
        AttachPoint = "",
        HashName = "WEAPON_PISTOL_VOLCANIC",
        Weight = 1.10,
    },
    WEAPON_PISTOL_M1899 = {
        Name = "Pistola M1899",
        Desc = "carregador permite um recarregamento rápido",
        AttachPoint = "",
        HashName = "WEAPON_PISTOL_M1899",
        Weight = 1.15,
    },
    WEAPON_REVOLVER_SCHOFIELD = {
        Name = "Revólver Schofield",
        Desc = "revólver de ação única, cartucho de quebra superior",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_SCHOFIELD",
        Weight = 1.30,
    },
    WEAPON_REVOLVER_NAVY = {
        Name = "Revólver Navy",
        Desc = "revólver de cápsula e bola, projetado por Samuel Colt",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_NAVY",
        Weight = 1.20,
    },
    WEAPON_REVOLVER_NAVY_CROSSOVER = {
        Name = "Revólver Navy Crossover",
        Desc = "um revólver que também é uma espingarda",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_NAVY_CROSSOVER",
        Weight = 1.25,
    },
    WEAPON_REVOLVER_LEMAT = {
        Name = "Revólver Lemat",
        Desc = "um revólver que também é uma espingarda",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_LEMAT",
        Weight = 1.86,
    },
    WEAPON_REVOLVER_DOUBLEACTION = {
        Name = "Revólver Double Action",
        Desc = "possui gatilho que arma e dispara com um só puxão",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_DOUBLEACTION",
        Weight = 0.94,
    },
    WEAPON_REVOLVER_CATTLEMAN = {
        Name = "Revólver Cattleman",
        Desc = "O melhor amigo do caubói",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_CATTLEMAN",
        Weight = 1.04,
    },
    WEAPON_REVOLVER_CATTLEMAN_MEXICAN = {
        Name = "Revólver Cattleman Mexicano",
        Desc = "uma variação diferente",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_CATTLEMAN_MEXICAN",
        Weight = 1.04,
    },
    WEAPON_RIFLE_VARMINT = {
        Name = "Rifle Varmint",
        Desc = "Um rifle útil para caçar pequenos animais",
        AttachPoint = "",
        HashName = "WEAPON_RIFLE_VARMINT",
        Weight = 3.80,
    },
    WEAPON_REPEATER_WINCHESTER = {
        Name = "Carabina Winchester",
        Desc = "rifles de repetição de ação de alavanca fabricados pela Winchester Repeating Arms Company",
        AttachPoint = "",
        HashName = "WEAPON_REPEATER_WINCHESTER",
        Weight = 4.30,
    },
    WEAPON_REPEATER_HENRY = {
        Name = "Carabina Henry",
        Desc = "rifle de repetição tubular de ação de alavanca",
        AttachPoint = "",
        HashName = "WEAPON_REPEATER_HENRY",
        Weight = 4.20,
    },
    WEAPON_REPEATER_EVANS = {
        Name = "Carabina Evans",
        Desc = "rifle de repetição de ação de alavanca projetado por Warren R. Evans como um rifle de alta capacidade",
        AttachPoint = "",
        HashName = "WEAPON_REPEATER_EVANS",
        Weight = 4.45,
    },
    WEAPON_REPEATER_CARBINE = {
        Name = "Carabina Buck",
        Desc = "Uma carabina popular e confiável, oferece dano médio e uma taxa de disparo decente",
        AttachPoint = "",
        HashName = "WEAPON_REPEATER_CARBINE",
        Weight = 4.10,
    },
    WEAPON_SNIPERRIFLE_ROLLINGBLOCK = {
        Name = "Rifle Rolling Block",
        Desc = "Remington Rolling Block, uma família de rifles de carregamento por culatra",
        AttachPoint = "",
        HashName = "WEAPON_SNIPERRIFLE_ROLLINGBLOCK",
        Weight = 4.20,
    },
    WEAPON_SNIPERRIFLE_CARCANO = {
        Name = "Rifle Carcano",
        Desc = "O Carcano é um rifle de ação de ferrolho italiano",
        AttachPoint = "",
        HashName = "WEAPON_SNIPERRIFLE_CARCANO",
        Weight = 3.62,
    },
    WEAPON_RIFLE_SPRINGFIELD = {
        Name = "Rifle Springfield",
        Desc = "Rifle padrão do exército",
        AttachPoint = "",
        HashName = "WEAPON_RIFLE_SPRINGFIELD",
        Weight = 3.90,
    },
    WEAPON_RIFLE_ELEPHANT = {
        Name = "Rifle Elefante",
        Desc = "Melhor arma para caçadores que buscam grandes presas",
        AttachPoint = "",
        HashName = "WEAPON_RIFLE_ELEPHANT",
        Weight = 12.50,
    },
    WEAPON_RIFLE_BOLTACTION = {
        Name = "Rifle Bolt Action",
        Desc = "ação manual de ferrolho manipulada diretamente",
        AttachPoint = "",
        HashName = "WEAPON_RIFLE_BOLTACTION",
        Weight = 4.08,
    },
    WEAPON_SHOTGUN_SEMIAUTO = {
        Name = "Espingarda Semi-Automática",
        Desc = "espingarda de repetição com ação semi-automática, capaz de carregar um novo cartucho automaticamente",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_SEMIAUTO",
        Weight = 3.53,
    },
    WEAPON_SHOTGUN_SAWEDOFF = {
        Name = "Espingarda Serrada",
        Desc = "espingarda com cano curto",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_SAWEDOFF",
        Weight = 1.90,
    },
    WEAPON_SHOTGUN_REPEATING = {
        Name = "Espingarda de Repetição",
        Desc = "A espingarda de repetição Lancaster",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_REPEATING",
        Weight = 3.60,
    },
    WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC = {
        Name = "Espingarda Exótica de Cano Duplo",
        Desc = "variante rara da espingarda de cano duplo",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC",
        Weight = 3.71,
    },
    WEAPON_SHOTGUN_PUMP = {
        Name = "Espingarda Pump",
        Desc = "ação de repetição manual com deslizamento",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_PUMP",
        Weight = 3.60,
    },
    WEAPON_SHOTGUN_DOUBLEBARREL = {
        Name = "Espingarda de Cano Duplo",
        Desc = "espingarda com ação de quebra e dois canos paralelos",
        AttachPoint = "",
        HashName = "WEAPON_SHOTGUN_DOUBLEBARREL",
        Weight = 3.65,
    },
    WEAPON_KIT_CAMERA = {
        Name = "Câmera",
        Desc = "a melhor amiga do jornalista",
        AttachPoint = "",
        HashName = "WEAPON_KIT_CAMERA",
        Weight = 0.47,
    },
    WEAPON_KIT_BINOCULARS_IMPROVED = {
        Name = "Binóculos Melhorados",
        Desc = "Veja as coisas com clareza!",
        AttachPoint = "",
        HashName = "WEAPON_KIT_BINOCULARS_IMPROVED",
        Weight = 1.50,
    },
    WEAPON_MELEE_KNIFE_TRADER = {
        Name = "Faca do Comerciante",
        Desc = "a melhor amiga do comerciante",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_KNIFE_TRADER",
        Weight = 0.45,
    },
    WEAPON_KIT_BINOCULARS = {
        Name = "Binóculos",
        Desc = "permite ver coisas distantes",
        AttachPoint = "",
        HashName = "WEAPON_KIT_BINOCULARS",
        Weight = 1.45,
    },
    WEAPON_KIT_CAMERA_ADVANCED = {
        Name = "Câmera Avançada",
        Desc = "uma câmera com leve aprimoramento tecnológico",
        AttachPoint = "",
        HashName = "WEAPON_KIT_CAMERA_ADVANCED",
        Weight = 0.55,
    },
    WEAPON_MELEE_LANTERN = {
        Name = "Lanterna",
        Desc = "ajuda a ver no escuro",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_LANTERN",
        Weight = 0.56,
    },
    WEAPON_MELEE_DAVY_LANTERN = {
        Name = "Lanterna Davy",
        Desc = "lanterna de segurança para atmosferas inflamáveis",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_DAVY_LANTERN",
        Weight = 0.65,
    },
    WEAPON_MELEE_LANTERN_HALLOWEEN = {
        Name = "Lanterna de Halloween",
        Desc = "feita com um crânio humano real",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_LANTERN_HALLOWEEN",
        Weight = 1.20,
    },
    WEAPON_THROWN_POISONBOTTLE = {
        Name = "Garrafa de Veneno",
        Desc = "quem sabe o que tem aqui dentro",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_POISONBOTTLE",
        Weight = 0.35,
    },
    WEAPON_KIT_METAL_DETECTOR = {
        Name = "Detector de Metais",
        Desc = "ajuda a encontrar itens valiosos",
        AttachPoint = "",
        HashName = "WEAPON_KIT_METAL_DETECTOR",
        Weight = 0.45,
    },
    WEAPON_THROWN_DYNAMITE = {
        Name = "Dinamite",
        Desc = "boomstick",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_DYNAMITE",
        Weight = 0.19,
    },
    WEAPON_THROWN_MOLOTOV = {
        Name = "Coquetel Molotov",
        Desc = "o melhor amigo do incendiário",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_MOLOTOV",
        Weight = 0.45,
    },
    WEAPON_BOW_IMPROVED = {
        Name = "Arco Melhorado",
        Desc = "um arco com melhor precisão",
        AttachPoint = "",
        HashName = "WEAPON_BOW_IMPROVED",
        Weight = 1.10,
    },
    WEAPON_MELEE_MACHETE_COLLECTOR = {
        Name = "Facão do Colecionador",
        Desc = "todo colecionador precisa de um",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_MACHETE_COLLECTOR",
        Weight = 1.40,
    },
    WEAPON_MELEE_LANTERN_ELECTRIC = {
        Name = "Lanterna Elétrica",
        Desc = "um avanço tecnológico",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_LANTERN_ELECTRIC",
        Weight = 0.95,
    },
    WEAPON_MELEE_TORCH = {
        Name = "Tocha",
        Desc = "um simples pedaço de madeira em chamas",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_TORCH",
        Weight = 1.50,
    },
    WEAPON_MOONSHINEJUG_MP = {
        Name = "Jarro de Moonshine",
        Desc = "esses são muito divertidos",
        AttachPoint = "",
        HashName = "WEAPON_MOONSHINEJUG_MP",
        Weight = 2.00,
    },
    WEAPON_THROWN_BOLAS = {
        Name = "Bolas",
        Desc = "todo caubói durão precisa de um",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_BOLAS",
        Weight = 0.55,
    },
    WEAPON_THROWN_BOLAS_HAWKMOTH = {
        Name = "Bolas Mariposa",
        Desc = "um tipo diferente de bolas",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_BOLAS_HAWKMOTH",
        Weight = 0.65,
    },
    WEAPON_THROWN_BOLAS_IRONSPIKED = {
        Name = "Bolas com Espinhos de Ferro",
        Desc = "uma versão mais agressiva",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_BOLAS_IRONSPIKED",
        Weight = 0.75,
    },
    WEAPON_THROWN_BOLAS_INTERTWINED = {
        Name = "Bolas Entrelaçadas",
        Desc = "uma bola mais resistente",
        AttachPoint = "",
        HashName = "WEAPON_THROWN_BOLAS_INTERTWINED",
        Weight = 0.60,
    },
    WEAPON_FISHINGROD = {
        Name = "Vara de Pesca",
        Desc = "o que é melhor do que pescar?",
        AttachPoint = "",
        HashName = "WEAPON_FISHINGROD",
        Weight = 1.10,
    },
    WEAPON_MACHETE_HORROR = {
        Name = "Facão Horror",
        Desc = "este realmente assusta as pessoas",
        AttachPoint = "",
        HashName = "WEAPON_MACHETE_HORROR",
        Weight = 1.40,
    },
    WEAPON_MELEE_HAMMER = {
        Name = "Martelo",
        Desc = "O Martelo do Richards!",
        AttachPoint = "",
        HashName = "WEAPON_MELEE_HAMMER",
        Weight = 1.25,
    },
    WEAPON_REVOLVER_DOUBLEACTION_GAMBLER = {
        Name = "Revólver Double-Action High Roller",
        Desc = "Revólver com motivos de apostas gravados",
        AttachPoint = "",
        HashName = "WEAPON_REVOLVER_DOUBLEACTION_GAMBLER",
        Weight = 1.05,
    },
}
